version: "3.7"
services:
  #service 1: definition of mysql database
  development-env:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: ubuntu-aws-img
    container_name: aws-container