version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8889:8888"
    volumes:
      - /sandbox/workspace/notebooks:/workspace
      - /sandbox/storage/data:/sandbox/storage/data
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Max 4 CPU cores
          memory: "8G"  # Max 8GB RAM
        reservations:
          cpus: "2.0"   # Guaranteed 2 CPU cores
          memory: "4G"  # Guaranteed 4GB RAM

