version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /sandbox/workspace/notebooks:/workspace
      - /sandbox/storage/data:/data
