version: "3.7"
services:
  #service 1: definition of mysql database
  airflow-env:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: airflow-server
    container_name: airflow-server
    ports:
      - "18082:8080"
    volumes:
      - ~/.aws:/root/.aws
      - ~/docker-share:/root/shared_drive
      - ~/aws-keys:/root/aws-keys
      - ~/airflow/dags:/root/airflow/dags