version: "3.7"
services:
  #service 1: definition of mysql database
  jdk-work-env:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: openjdk11.0.11-jre-slim-buster
    container_name: docker-dev-env