version: "3.7"
services:
  #service 1: definition of mysql database
  development-env:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: ubuntu-development-env
    container_name: ubuntu-env
    volumes:
      - ~/.aws:/root/.aws
      - ~/docker-share:/root/shared_drive
      - ~/aws-keys:/root/aws-keys